spring.application.name=demo

spring.datasource.password = *

spring.datasource.username = postgres

spring.jpa.hibernate.ddl-auto = update

spring.datasource.url = jdbc:postgresql://localhost:3030/twitter-database

server.port = 3232
